### ISSUE TITLE
JAPANESE

### ISSUE THREAD

**Issue by KrisMerckx** [Setasign/FPDI-FPDF#3]
Hello

A real strange thing happens... when I add the class "class PDF_Japanese extends FPDI", FDPI converts Japanese to Chinese characters :-)

I used this script: https://github.com/Trouble-Shooters/ts4/blob/master/module/fpdi/japanese.php

**Comment by JanSlabon** [comment]
I'm really sorry but what kind of reply do you expect from this post? I mean there's not a single question ;-)

If you really think that this is an issue of FPDI, please prepare a complete reproducable test case and post the issue to the official [FPDI repository](https://github.com/Setasign/FPDI/issues). This package is only a metadata package.
